# Generated by Django 6.0.1 on 2026-01-21 04:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_created_at_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'user')},
        ),
    ]
